export default [
  {
    id: 1,
    startDate: '02.03',
    endDate: '06.03',
    days: {
      wed: 'Dowiedz się, kiedy w kościele blisko Twojego mieszkania odbywa się droga krzyżowa i zapisz to w kalendarzu oraz zaplanuj uczestnictwo w rekolekcjach (na żywo lub przez internet).',
      thu: 'Wybierz z PŚ fragment zachęcający do pracy nad sobą; przepisz go i powieś w widocznym miejscu.',
      fri: 'Zaplanuj uczestnictwo w rekolekcjach wielkopostnych; jeżeli to niemożliwe, zaplanuj słuchanie rekolekcji dostępnych w internecie.',
      sat: 'Przeczytaj punkty 1–41 encykliki Fratelli Tutti',
      sun: 'Zastanów się, na jaki cel przeznaczysz swoją jałomużnę (może jakaś zbiórka, np. ze strony Caritasu); przygotuj notes do jej zapisywania.',
    },
  },
  {
    id: 2,
    startDate: '07.03',
    endDate: '13.03',
    days: {
      mon: 'Zadbaj, żeby dziś modlitwa była pierwszą rzeczą, którą zrobisz po przebudzeniu.',
      tue: 'Włącz się w akcję pomocową dla potrzebujących (np. pójdź jako wolontariusz do kuchni dla bezdomnych, oddaj ubranie na zbiórkę); następnie przeczytaj Mt 25,40.',
      wed: 'Zadbaj o dobry sen; w szczególności nie używaj elektroniki przez godzinę przed pójściem spać.',
      thu: 'Poświęć przynajmniej 15 minut na przeczytanie 1 Tes 5, 12-22 i rozmyślanie o tym fragmencie.',
      fri: 'Spróbuj spędzić godzinę w ciszy.',
      sat: 'Przeczytaj punkty 42–83 encykliki Fratelli Tutti',
      sun: 'Przez cały dzień bądź ubrany odświętnie.',
    },
  },
  {
    id: 3,
    startDate: '14.03',
    endDate: '20.03',
    days: {
      mon: 'Zakończ dzień rachunkiem sumienia (z dnia) i modlitwą.',
      tue: 'Za każdym razem, gdy ktoś cię zdenerwuje, pomódl się za niego "Zdrowaś Mario...".',
      wed: 'Ustal dzisiejszy plan dnia. Uwzględnij czas na spełnianie obowiązków, posiłki, odpoczynek i sen.',
      thu: 'Zaplanuj czas (min. 10 minut) na rozważanie słowa Bożego. Do rozważenia proponujemy Kpł 19, 1-2. 11-18.',
      fri: 'Podejmij jakiś dodatkowe wyrzeczenie pokarmowe (lub inne).',
      sat: 'Przeczytaj punkty 84–127 encykliki Fratelli Tutti',
      sun: 'Wyberz się dziś na godzinny spacer, podczas którego nie będziesz używał telefonu.',
    },
  },
  {
    id: 4,
    startDate: '21.03',
    endDate: '27.03',
    days: {
      mon: '',
      tue: '',
      wed: '',
      thu: '',
      fri: '',
      sat: '',
      sun: '',
    },
  },
  {
    id: 5,
    startDate: '28.03',
    endDate: '03.04',
    days: {
      mon: '',
      tue: '',
      wed: '',
      thu: '',
      fri: '',
      sat: '',
      sun: '',
    },
  },
  {
    id: 6,
    startDate: '04.04',
    endDate: '10.04',
    days: {
      mon: '',
      tue: '',
      wed: '',
      thu: '',
      fri: '',
      sat: '',
      sun: '',
    },
  },
  {
    id: 7,
    startDate: '11.04',
    endDate: '17.04',
    days: {
      mon: '',
      tue: '',
      wed: '',
      thu: '',
      fri: '',
      sat: '',
      sun: '',
    },
  },
]
