export default [
  {
    id: 1,
    startDate: '02.03',
    endDate: '06.03',
    days: {
      wed: 'Dowiedz się, kiedy w kościele blisko Twojego mieszkania odbywa się droga krzyżowa i zapisz to w kalendarzu oraz zaplanuj uczestnictwo w rekolekcjach (na żywo lub przez internet).',
      thu: 'Wybierz z PŚ fragment zachęcający do pracy nad sobą; przepisz go i powieś w widocznym miejscu.',
      fri: 'Zaplanuj uczestnictwo w rekolekcjach wielkopostnych; jeżeli to niemożliwe, zaplanuj słuchanie rekolekcji dostępnych w internecie.',
      sat: 'Przeczytaj punkty 1–41 encykliki Fratelli Tutti',
      sun: 'Zastanów się, na jaki cel przeznaczysz swoją jałomużnę (może jakaś zbiórka, np. ze strony Caritasu); przygotuj notes do jej zapisywania.',
    },
  },
  {
    id: 2,
    startDate: '07.03',
    endDate: '13.03',
    days: {
      mon: 'Zadbaj, żeby dziś modlitwa była pierwszą rzeczą, którą zrobisz po przebudzeniu.',
      tue: 'Włącz się w akcję pomocową dla potrzebujących (np. pójdź jako wolontariusz do kuchni dla bezdomnych, oddaj ubranie na zbiórkę); następnie przeczytaj Mt 25,40.',
      wed: 'Zadbaj o dobry sen; w szczególności nie używaj elektroniki przez godzinę przed pójściem spać.',
      thu: 'Poświęć przynajmniej 15 minut na przeczytanie 1 Tes 5, 12-22 i rozmyślanie o tym fragmencie.',
      fri: 'Spróbuj spędzić godzinę w ciszy.',
      sat: 'Przeczytaj punkty 42–83 encykliki Fratelli Tutti',
      sun: 'Przez cały dzień bądź ubrany odświętnie.',
    },
  },
  {
    id: 3,
    startDate: '14.03',
    endDate: '20.03',
    days: {
      mon: 'Zakończ dzień rachunkiem sumienia (z dnia) i modlitwą.',
      tue: 'Za każdym razem, gdy ktoś cię zdenerwuje, pomódl się za niego "Zdrowaś Mario...".',
      wed: 'Ustal dzisiejszy plan dnia. Uwzględnij czas na spełnianie obowiązków, posiłki, odpoczynek i sen.',
      thu: 'Zaplanuj czas (min. 10 minut) na rozważanie słowa Bożego. Do rozważenia proponujemy Kpł 19, 1-2. 11-18.',
      fri: 'Podejmij jakiś dodatkowe wyrzeczenie pokarmowe (lub inne).',
      sat: 'Przeczytaj punkty 84–127 encykliki Fratelli Tutti',
      sun: 'Wyberz się dziś na godzinny spacer, podczas którego nie będziesz używał telefonu.',
    },
  },
  {
    id: 4,
    startDate: '21.03',
    endDate: '27.03',
    days: {
      mon: 'Dowiedz czym jest akt strzelisty; pomódl się w ciągu dnia w ten sposób.',
      tue: 'Pomódl się koronką do Bożego miłosierdzia w intencji wybranej osoby lub grupy.',
      wed: 'Przyjdź dziś na Mszę Świetą.',
      thu: 'Dowiedz się na czym polega Lectio Divina i pomódl się w ten sposób.',
      fri: 'Przyjdź na Drogę Krzyżową.',
      sat: 'Przeczytaj punkty 128–169 encykliki Fratelli Tutti',
      sun: 'Przed przyjściem na Mszę zapoznaj się z czytaniami.',
    },
  },
  {
    id: 5,
    startDate: '28.03',
    endDate: '03.04',
    days: {
      mon: 'W modlitwie wieczornej podziękuj Bogu za swoich przyjaciół.',
      tue: 'Skontaktuj się ze znajomym, z którym dawno nie rozmawiałeś.',
      wed: 'Przygotuj kartkę świąteczną z życzeniami dla kogoś bliskiego.',
      thu: 'Poświęć przynajmniej 15 minut na przeczytanie Syr 6,5–16 i rozmyślanie o tym fragmencie.',
      fri: 'Podziel się małym świadectwem, radością lub przeżyciem duchowym z bliźnim.',
      sat: 'Przeczytaj punkty 170–214 encykliki Fratelli Tutti',
      sun: 'Spotkaj się z przyjaciółmi.',
    },
  },
  {
    id: 6,
    startDate: '04.04',
    endDate: '10.04',
    days: {
      mon: 'Zastanów się, jaką szczególną dobrą cechę posiada osoba, która Cię irytuje i podziękuj za nią Bogu.',
      tue: 'W czasie modlitwy (np. przed Najświętszym Sakramentem) pomyśl o kimś, kto Cię zranił i postaraj się mu wybaczyć.',
      wed: 'Postaraj się dziś okazywać innym wdzięczność.',
      thu: 'Poświęć przynajmniej 15 minut na przeczytanie Mt 5, 43–48 i rozmyślanie o tym fragmencie.',
      fri: 'Podejmij post w intencji osób trwających w grzechu ciężkim.',
      sat: 'Przeczytaj punkty 215–254 encykliki Fratelli Tutti',
      sun: 'Postaraj się dzisiaj nieść radość napotykanym osobom przez proste gesty (np. uśmiech, miłe słowo, drobną pomoc).',
    },
  },
  {
    id: 7,
    startDate: '11.04',
    endDate: '17.04',
    days: {
      mon: '',
      tue: '',
      wed: '',
      thu: '',
      fri: '',
      sat: '',
      sun: '',
    },
  },
]
